### PR TITLE
Add an option to pass a filename to (Re)store settings.

### PR DESCRIPTION
**Pull request by Tiksi**
I have a use case where I'd like to swap between a few different sets of settings for the camera. To facilitate this, I've added an optional filename argument to the `-s` (store) and `-r` (restore) options.

Here are the changes I've made:

1. The `-s` and `-r` command line options can now take an optional filename as an argument. If specified, the current parameter values will be stored to or restored from this file. If no filename is specified, the program will default to the existing behavior of using a file named '.pyvidctrl-' followed by the driver name.

2. The `store_ctrls` and `restore_ctrls` methods in the App class have been updated to accept an optional filename argument.

3. The help text for the `-s` and `-r` options has been updated to reflect these changes.

4. I've updated the README.md to include a section on command line options, which details the usage of the `-r`, `-s`, and `-d` options. This provides users with a clear understanding of how they can use these options to control the behavior of the program.

These changes provide users with greater flexibility when using pyvidctrl, especially in use cases where there are multiple sets of camera settings that need to be regularly switched between.

### CODE REVIEW

**Comment by Tiksi** [comment]
> Hi,
> 
> I missed your PR, sorry for the delay! The change looks good and makes sense!
> 
> Could you please take care of the formatting (the CI is red because flake8 is failing)? Then we can merge this PR.
> 
> Thanks!

Sorry didn't notice you replied, my bad. It looks like flake8 is failing to install, not due to formatting:

```

Run actions/setup-python@v2
Version 3.9.4 was not found in the local cache
Error: Version 3.9.4 with arch x64 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

**Comment by tgorochowik** [comment]
Force pushed your branch to restart the CI

**Comment by tgorochowik** [comment]
Changed the python version requirement to a less specific version (and bumped to 3.10 as this is the one currently recommended by the setup python gh action)

**Comment by tgorochowik** [comment]
Sorry for the big delay here, the CI checks were failing for your code, I've migrated the check to use yapf instead of flake (to be able to auto fix those).

Thank you for the contribution! Merging

**Review by tgorochowik — APPROVED** [review]

**Pull request merged**
